version: 2
updates:
  - package-ecosystem: "flutter"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"
    commit-message:
      prefix: "build: "
      include: "scope"
