blank_issues_enabled: false
contact_links:
  - name: FluffyChat Community
    url: https://matrix.to/#/#fluffychat:matrix.org
    about: Please ask and answer questions here.
  - name: Report security vulnerabilities
    url: https://matrix.to/#/@krille:janian.de
    about: Please report security vulnerabilities here.
