name: 💡 Feature Request
description: Suggest an idea for this project
labels: ["Enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: "Feature Description"
      description: "Provide a clear and concise description of the feature."
      placeholder: "Describe the feature here..."
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: "Rationale"
      description: "Explain why this feature should be added."
      placeholder: "Describe the rationale for the feature here..."
    validations:
      required: true
  - type: textarea
    id: functionality
    attributes:
      label: "Functionality"
      description: "Describe what the feature would do and how it should work."
      placeholder: "Describe the functionality of the feature here..."
    validations:
      required: true
  - type: input
    id: mockup
    attributes:
      label: "Mockup"
      description: "If applicable, add any visual mock-ups of the feature."
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
