name: Flutter Analyze

on: [push, pull_request]

env:
  FLUTTER_VERSION: '3.10.6'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - name: Check formatting
        run: dart format lib/ test/ --set-exit-if-changed
      - name: Check import formatting
        run: dart run import_sorter:main --no-comments --exit-if-changed
      - run: flutter analyze
      - name: Apply google services patch
        run: git apply ./scripts/enable-android-google-services.patch
      - run: flutter analyze

