name: Auto merge

on: pull_request_target

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'dependabot[bot]' || github.actor == 'weblate'
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: rebase