name: Weblate Auto Merge

on:
  pull_request:
    types: [opened, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'weblate'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
